### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by msureda** [pypa/packaging-problems#438]
1. What is your operating system and version?
Ubuntu  18.04
```
$ uname -v
#73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021
```

2. What is your Python version?
```
$ python -V
Python 3.6.9

```
3. What version of pip do you have?
```
$ python -m pip --version
pip 21.0.1 from /home/marcelo/workspace-pyvcloud-git/packaging_tutorial/.venv/lib/python3.6/site-packages/pip (python 3.6)

```
4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
I'm following this [tutorial](https://packaging.python.org/tutorials/packaging-projects/)

5. Could you describe your issue in as much detail as possible?
I follow the same exact steps indicated in the tutorial, and I have the following set up in the project:
```
$ tree .
.
├── example_pkg
│   └── __init__.py
├── LICENSE
├── pyproject.toml
├── README.md
├── setup.cfg
├── setup.py
└── tests
```

After successfully installing the latest versions of PyPA’s build, I try to build the distribution files but got the following errors:
```
$ python -m build 
Uninstalling setuptools-39.0.1:
  Successfully uninstalled setuptools-39.0.1

Usage:   
  /tmp/build-env-iqsckeaf/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /tmp/build-env-iqsckeaf/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /tmp/build-env-iqsckeaf/bin/python -m pip install [options] [-e] <vcs project url> ...
  /tmp/build-env-iqsckeaf/bin/python -m pip install [options] [-e] <local project path> ...
  /tmp/build-env-iqsckeaf/bin/python -m pip install [options] <archive url/path> ...

no such option: --no-warn-script-location
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/marcelo/workspace-pyvcloud-git/packaging_tutorial/.venv/lib/python3.6/site-packages/build/__main__.py", line 213, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/home/marcelo/workspace-pyvcloud-git/packaging_tutorial/.venv/lib/python3.6/site-packages/build/__main__.py", line 205, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/home/marcelo/workspace-pyvcloud-git/packaging_tutorial/.venv/lib/python3.6/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/home/marcelo/workspace-pyvcloud-git/packaging_tutorial/.venv/lib/python3.6/site-packages/build/__main__.py", line 56, in _build_in_isolated_env
    env.install(builder.build_dependencies)
  File "/home/marcelo/workspace-pyvcloud-git/packaging_tutorial/.venv/lib/python3.6/site-packages/build/env.py", line 142, in install
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-iqsckeaf/bin/python', '-Im', 'pip', 'install', '--no-warn-script-location', '-r', '/tmp/build-reqs-1g82pkzl.txt']' returned non-zero exit status 2.

```
It seems that pip doesn't recognize the option '--no-warn-script-location' but if I run pip in the shell directly with that same option, it runs ok. 

Any help would be greatly appreciated.

**Comment by msureda** [comment]
A quick update on the issue. I made a change in the file .venv/lib/python3.6/site-packages/build/env.py. I commented out the line with the option --no-warn-script-location in the method install of class _IsolatedEnvVenvPip, as it's shown below:

```
        with tempfile.NamedTemporaryFile('w+', prefix='build-reqs-', suffix='.txt', delete=False) as req_file:
            req_file.write(os.linesep.join(requirements))
        try:
            cmd = [
                self.executable,
                '-{}m'.format('E' if sys.version_info[0] == 2 else 'I'),
                'pip',
                'install',
#                '--no-warn-script-location',
                '-r',
                os.path.abspath(req_file.name),
            ]
            subprocess.check_call(cmd)
        finally:
            os.unlink(req_file.name)

```

With that line commented out finally finished successfully the distribution build procedure:

```
$ tree .
.
├── build
│   └── bdist.linux-x86_64
├── dist
│   ├── example_pkg_msureda_test-0.0.1-py3-none-any.whl
│   └── example-pkg-msureda-test-0.0.1.tar.gz
├── example_pkg
│   └── __init__.py
├── example_pkg_msureda_test.egg-info
│   ├── dependency_links.txt
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   └── top_level.txt
...

Maybe there's something broken in my venv, but I can't figure out what's wrong. So if anyone can take a look at this, I'll appreciate it.
Thanks.

**Comment by merwok** [comment]
I don’t know why the tutorial recommends using python-build rather than pip.

**Comment by henryiii** [comment]
This was a bug in build 0.2.0 fixed in 0.2.1, I think. https://github.com/pypa/build/pull/227 . Upgrading build should fix the problem.

**Comment by henryiii** [comment]
Fully fixed in https://github.com/pypa/build/pull/229 if not fixed already. Ubuntu 18.04 mixes unhealthy, unsanctioned versions of pip and Python into its venv package.

**Comment by msureda** [comment]
Thank you @henryiii but I'm still getting the same error using Python 3.6, which is the version I need to keep in my project. Maybe is related with the way the Python pip and build versions are packaged in Ubuntu 18.04, so I won't follow the tutorial and I'll use setuptools commands, which are working fine.

**Comment by henryiii** [comment]
A new release of build has not been made yet. As soon as that is, it will start working on Ubuntu 18.04 out of the box. Ubuntu mixes newer Python versions with old pip versions in a way that is not supported. You can fix it by installing virtualenv, btw, and it's a bit faster too.

**Comment by henryiii** [comment]
Fixed in build 0.3.0! Please reopen if there are still issues.
