### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by dagewa** [pypa/packaging-problems#441]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Ubuntu 18.04.2 LTS (beaver-osp1-gendry X45)

2. What is your Python version?

Python 3.6.9

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives

5. Could you describe your issue in as much detail as possible?

The build step fails for me, using the system python3:
```
$ python3 -m build
Uninstalling setuptools-39.0.1:
  Successfully uninstalled setuptools-39.0.1

Usage:   
  /tmp/build-env-aqsi8iut/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /tmp/build-env-aqsi8iut/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /tmp/build-env-aqsi8iut/bin/python -m pip install [options] [-e] <vcs project url> ...
  /tmp/build-env-aqsi8iut/bin/python -m pip install [options] [-e] <local project path> ...
  /tmp/build-env-aqsi8iut/bin/python -m pip install [options] <archive url/path> ...

no such option: --no-warn-script-location
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fcx32934/.local/lib/python3.6/site-packages/build/__main__.py", line 213, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/home/fcx32934/.local/lib/python3.6/site-packages/build/__main__.py", line 205, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/home/fcx32934/.local/lib/python3.6/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/home/fcx32934/.local/lib/python3.6/site-packages/build/__main__.py", line 56, in _build_in_isolated_env
    env.install(builder.build_dependencies)
  File "/home/fcx32934/.local/lib/python3.6/site-packages/build/env.py", line 142, in install
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-aqsi8iut/bin/python', '-Im', 'pip', 'install', '--no-warn-script-location', '-r', '/tmp/build-reqs-3e5nuxg2.txt']' returned non-zero exit status 2.

```

**Comment by dagewa** [comment]
My issue looks very similar (identical?) to #438

**Comment by henryiii** [comment]
This is a bug in build, https://github.com/pypa/build/issues/226 , which was fixed in https://github.com/pypa/build/pull/227 and released two hours ago. Please retry. :)

**Comment by FFY00** [comment]
Hi, this was fixed in https://github.com/pypa/build/pull/227 and should be available in `build` 0.2.1.

**Comment by henryiii** [comment]
It's fully fixed in https://github.com/pypa/build/pull/229; Ubuntu 18.04 does evil things with mixing Pythons and venv Pip's that should not go together.

**Comment by dagewa** [comment]
I'm still seeing the same issue with `build` 0.2.1, but looking at the conversation above that seems expected and I should wait to try 0.2.2 I guess?

**Comment by layday** [comment]
Yeah, this wasn't fixed for Ubuntu in 0.2.1.  I expect there's going to be a new release soon to address this and another issue with isolation.

**Comment by henryiii** [comment]
Fixed in build 0.3.0! Please reopen if there are still issues.

**Comment by dagewa** [comment]
That's great, thanks. I've confirmed `python3 -m build` works for me :+1: (though the [tutorial webpage](https://packaging.python.org/tutorials/packaging-projects/) no longer refers to `build`)

**Comment by layday** [comment]
> though the [tutorial webpage](https://packaging.python.org/tutorials/packaging-projects/) no longer refers to `build`

It still does for me under "Generating distribution archives" - is that not the case for you?

**Comment by dagewa** [comment]
I see `python3 setup.py sdist bdist_wheel` but not `python3 -m build` any more - but I guess at this point I should be starting again with the tutorial...

**Comment by henryiii** [comment]
You should never call setup.py directly.

**Comment by dagewa** [comment]
I suppose the [current tutorial page](https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives) advocates bad practice then?
![setup py](https://user-images.githubusercontent.com/11502083/108537901-107b0e80-72d6-11eb-882e-ccd856bac55f.png)

**Comment by henryiii** [comment]
This looks like a very old version of the page?

**Comment by dagewa** [comment]
I... don't know... I've refreshed it a few times :thinking:

**Comment by henryiii** [comment]
Maybe they didn't fix the RtD integration? I'll check when I'm at a computer.

**Comment by dagewa** [comment]
The source .rst looks right https://github.com/pypa/packaging.python.org/blob/main/source/tutorials/packaging-projects.rst. I'll just follow that. Thanks.

**Comment by FFY00** [comment]
FWIW, I also see `python3 setup.py sdist bdist_wheel`. @di is it possible something is going on with the infrastructure?

**Comment by di** [comment]
I'm not sure what's going on. The builds seem to be correctly triggered, and I just [re-ran](https://readthedocs.org/projects/python-packaging-user-guide/builds/13062042/) the latest and it was successful. Can someone file an issue at https://github.com/pypa/packaging.python.org/?

**Comment by di** [comment]
The latest PDF seems to have the right content: https://packaging.python.org/_/downloads/en/latest/pdf/

**Comment by di** [comment]
And now that I say that, I'm now seeing the right content on https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives (I think). Not sure what happened there.

**Comment by henryiii** [comment]
Yes, looks fine again to me now.
