### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by trishamck** [pypa/packaging-problems#443]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

 Windows 10 .

2. What is your Python version?

Python 3.8.5. 

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/ 
at step:
_**Now run this command from the same directory where pyproject.toml is located:

python3 -m build

This command should output a lot of text and once completed should generate two files in the dist directory:

dist/
  example_pkg_YOUR_USERNAME_HERE-0.0.1-py3-none-any.whl
  example_pkg_YOUR_USERNAME_HERE-0.0.1.tar.gz

Note

If you run into trouble here, please copy the output and file an issue over on packaging problems and we’ll do our best to help you!**_ 

5. Could you describe your issue in as much detail as possible?

C:\Users\USER\PycharmProjects\packaging_tutorial>
Found existing installation: setuptools 49.2.1
Uninstalling setuptools-49.2.1:
  Successfully uninstalled setuptools-49.2.1
Collecting setuptools>=42
  Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools, wheel
Successfully installed setuptools-53.0.0 wheel-0.36.2
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\Scripts\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517\_in_process.py", line 280, in <module>
    main()
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517\_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517\_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\lib\site-packages\setuptools\build_meta.py", line 220, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\lib\site-packages\setuptools\build_meta.py", line 204, in _build_with_temp_dir
    result_basename = _file_with_extension(
  File "C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\lib\site-packages\setuptools\build_meta.py", line 104, in _file_with_extension
    file, = matching
ValueError: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\USER\\AppData\\Local\\Temp\\build-env-gpmgxugw\\Scripts\\python.exe', 'C:\\Users\\USER\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\USER\\AppData\\Local\\Temp\\tmps4uxr5iq']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\build\__init__.py", line 275, in build
    raise BuildBackendException('Backend operation failed: {!r}'.format(e))
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['C:\\Users\\USER\\AppData\\Local\\Temp\\build-env-gpmgxugw\\Scripts\\python.exe', 'C:\\Users\\USER\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\USER\\AppData\\Local\\Temp\\tmps4uxr5iq'])

[91mERROR[0m Backend operation failed: CalledProcessError(1, ['C:\\Users\\USER\\AppData\\Local\\Temp\\build-env-gpmgxugw\\Scripts\\python.exe', 'C:\\Users\\USER\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\USER\\AppData\\Local\\Temp\\tmps4uxr5iq'])

**Comment by henryiii** [comment]
Can you please use triple tick marks around the output, so it's easier to read? Thanks!

**Comment by trishamck** [comment]
Hi Henry!
Like this:
'''C:\Users\USER\PycharmProjects\packaging_tutorial>
Found existing installation: setuptools 49.2.1
Uninstalling setuptools-49.2.1:
Successfully uninstalled setuptools-49.2.1
Collecting setuptools>=42
Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
Collecting wheel
Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools, wheel
Successfully installed setuptools-53.0.0 wheel-0.36.2
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\Scripts\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517_in_process.py", line 280, in
main()
File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517_in_process.py", line 263, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517_in_process.py", line 236, in build_sdist
return backend.build_sdist(sdist_directory, config_settings)
File "C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\lib\site-packages\setuptools\build_meta.py", line 220, in build_sdist
return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
File "C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\lib\site-packages\setuptools\build_meta.py", line 204, in _build_with_temp_dir
result_basename = _file_with_extension(
File "C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\lib\site-packages\setuptools\build_meta.py", line 104, in _file_with_extension
file, = matching
ValueError: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\Scripts\python.exe', 'C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517\_in_process.py', 'build_sdist', 'C:\Users\USER\AppData\Local\Temp\tmps4uxr5iq']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\build_init_.py", line 275, in build
raise BuildBackendException('Backend operation failed: {!r}'.format(e))
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\Scripts\python.exe', 'C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517\_in_process.py', 'build_sdist', 'C:\Users\USER\AppData\Local\Temp\tmps4uxr5iq'])

�[91mERROR�[0m Backend operation failed: CalledProcessError(1, ['C:\Users\USER\AppData\Local\Temp\build-env-gpmgxugw\Scripts\python.exe', 'C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517\_in_process.py', 'build_sdist', 'C:\Users\USER\AppData\Local\Temp\tmps4uxr5iq'])'''

**Comment by henryiii** [comment]
No, the little character at the top left of the (US) keyword, the backtick. See here: https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

**Comment by henryiii** [comment]
And, from trying to read the above output, I think this is another manifestation of #436 which would be fixed by pypa/packaging.python.org#823

**Comment by trishamck** [comment]
Ah - ok  - I see the backtick - will use that in the future.  I will also take a look at the url you sent me for the fix.  Thanks!

**Comment by henryiii** [comment]
Yes, it's missing a setting in `[options]`, you need `packages = find:`, otherwise there are no packages and it doesn't have anything to do. I missed that when merging at some point when updating the tutorial.

**Comment by henryiii** [comment]
Should be fixed in the current tutorial!

**Comment by trishamck** [comment]
Hi henryiii, I have updated my packaging_tutorial with the data from the latest tutorial.  I am still getting issues:
```C:\Users\USER1\PycharmProjects\packaging_tutorial>python3 -m build
Found existing installation: setuptools 49.2.1
Uninstalling setuptools-49.2.1:
  Successfully uninstalled setuptools-49.2.1
Collecting setuptools>=42
  Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools, wheel
Successfully installed setuptools-53.0.0 wheel-0.36.2
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\USER1\AppData\Local\Temp\build-env-2c3c6fsw\Scripts\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Users\USER1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517\_in_process.py", line 280, in <module>
    main()
  File "C:\Users\USER1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517\_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\USER1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pep517\_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "C:\Users\USER1\AppData\Local\Temp\build-env-2c3c6fsw\lib\site-packages\setuptools\build_meta.py", line 220, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "C:\Users\USER1\AppData\Local\Temp\build-env-2c3c6fsw\lib\site-packages\setuptools\build_meta.py", line 204, in _build_with_temp_dir
    result_basename = _file_with_extension(
  File "C:\Users\USER1\AppData\Local\Temp\build-env-2c3c6fsw\lib\site-packages\setuptools\build_meta.py", line 104, in _file_with_extension
    file, = matching
ValueError: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\USER1\\AppData\\Local\\Temp\\build-env-2c3c6fsw\\Scripts\\python.exe', 'C:\\Users\\USER1\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\USER1\\AppData\\Local\\Temp\\tmppu8vupx6']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\build\__init__.py", line 275, in build
    raise BuildBackendException('Backend operation failed: {!r}'.format(e))
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['C:\\Users\\USER1\\AppData\\Local\\Temp\\build-env-2c3c6fsw\\Scripts\\python.exe', 'C:\\Users\\USER1\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\USER1\\AppData\\Local\\Temp\\tmppu8vupx6'])

[91mERROR[0m Backend operation failed: CalledProcessError(1, ['C:\\Users\\USER1\\AppData\\Local\\Temp\\build-env-2c3c6fsw\\Scripts\\python.exe', 'C:\\Users\\USER1\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\USER1\\AppData\\Local\\Temp\\tmppu8vupx6'])```

here is my directory: 
```02/09/2021  04:48 PM    <DIR>          .
02/09/2021  04:48 PM    <DIR>          ..
02/09/2021  04:47 PM    <DIR>          dist
02/09/2021  04:01 PM    <DIR>          example_pkg
02/09/2021  10:53 AM             1,091 LICENSE
02/09/2021  09:02 AM               108 pyproject.toml
02/09/2021  09:22 AM               173 README.md
02/09/2021  03:55 PM               531 setup.cfg
02/09/2021  09:00 AM                 0 setup.py
02/09/2021  08:56 AM    <DIR>          tests```

example_pkg has the following file in it:

```C:\Users\USER1\PycharmProjects\packaging_tutorial\example_pkg>more __init__.py
# package indicator```

I am not sure what might be wrong.  If you need any more information please let me know...

Many Thanks, Trish

**Comment by henryiii** [comment]
Can you paste your setup.cfg ? Also, your setup.py is empty; putting `import setuptools; setuptools.setup()` in it is slightly better (though you could also just remove it).

**Comment by trishamck** [comment]
Well - you found the solution:  As soon as I put ```import setuptools; setuptools.setup() into setup.py``` it ran perfectly .  Thanks for all your help - you are my hero!

**Comment by henryiii** [comment]
I've tried to improve the docs a bit in https://github.com/pypa/packaging.python.org/pull/829 to avoid this mistake.
